#!/usr/bin/env bash

filename=/tmp/`date +%s%N`.mp4
outfile=$(basename $filename .mp4).gif
rectangle=`ffmpeg-get-rect`
[[ "$rectangle" != "" ]] && ffmpeg $rectangle $@ $filename && ffmpeg -i $filename $(basename $filename .mp4).gif && gyazo $outfile && rm $filename $outfile
